### ISSUE TITLE
TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by milewski** [scopsy/node-typescript-starter#4]
Hey guys could we get this starter updated? im trying to update to `tsed` but im failing hard...

```
TypeError: Cannot read property 'get' of undefined
at new ConverterService (/Users/milewski/Code/backend/node_modules/@tsed/src/common/converters/services/ConverterService.ts:21:53)
at Function.invoke (/Users/milewski/Code/backend/node_modules/@tsed/src/common/di/services/InjectorService.ts:277:16)
at registry.forEach.provider (/Users/milewski/Code/backend/node_modules/@tsed/src/common/di/services/InjectorService.ts:359:53)
at Map.forEach (<anonymous>)
at Registry.forEach (/Users/milewski/Code/backend/node_modules/@tsed/src/core/class/Registry.ts:140:19)
at Function.buildRegistry (/Users/milewski/Code/backend/node_modules/@tsed/src/common/di/services/InjectorService.ts:357:18)
at Function.<anonymous> (/Users/milewski/Code/backend/node_modules/@tsed/src/common/di/services/InjectorService.ts:443:14)
at Generator.next (<anonymous>)
at /Users/milewski/Code/backend/node_modules/tslib/tslib.js:107:75
at new Promise (<anonymous>)
at Object.__awaiter (/Users/milewski/Code/backend/node_modules/tslib/tslib.js:103:16)
at Function.load (/Users/milewski/Code/backend/node_modules/@tsed/common/lib/di/services/InjectorService.js:350:24)
at InjectorService.<anonymous> (/Users/milewski/Code/backend/node_modules/@tsed/src/common/di/services/InjectorService.ts:209:32)
at Generator.next (<anonymous>)
at /Users/milewski/Code/backend/node_modules/tslib/tslib.js:107:75
at new Promise (<anonymous>)
(node:2952) DeprecationWarning: Use registerFactory() util instead of
(node:2952) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'get' of undefined
at new ConverterService (/Users/milewski/Code/backend/node_modules/@tsed/src/common/converters/services/ConverterService.ts:21:53)
at Function.invoke (/Users/milewski/Code/backend/node_modules/@tsed/src/common/di/services/InjectorService.ts:277:16)
at registry.forEach.provider (/Users/milewski/Code/backend/node_modules/@tsed/src/common/di/services/InjectorService.ts:359:53)
at Map.forEach (<anonymous>)
at Registry.forEach (/Users/milewski/Code/backend/node_modules/@tsed/src/core/class/Registry.ts:140:19)
at Function.buildRegistry (/Users/milewski/Code/backend/node_modules/@tsed/src/common/di/services/InjectorService.ts:357:18)
at Function.<anonymous> (/Users/milewski/Code/backend/node_modules/@tsed/src/common/di/services/InjectorService.ts:443:14)
at Generator.next (<anonymous>)
at /Users/milewski/Code/backend/node_modules/tslib/tslib.js:107:75
at new Promise (<anonymous>)
at Object.__awaiter (/Users/milewski/Code/backend/node_modules/tslib/tslib.js:103:16)
at Function.load (/Users/milewski/Code/backend/node_modules/@tsed/common/lib/di/services/InjectorService.js:350:24)
at InjectorService.<anonymous> (/Users/milewski/Code/backend/node_modules/@tsed/src/common/di/services/InjectorService.ts:209:32)
at Generator.next (<anonymous>)
at /Users/milewski/Code/backend/node_modules/tslib/tslib.js:107:75
at new Promise (<anonymous>)
(node:2952) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
(node:2952) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    [nodemon] clean exit - waiting for changes before restart

```

**Comment by heralight** [comment]
Hi,
check my push request...

**Comment by Paul75** [comment]
In you push I'v got error : 
```
[2018-11-03T13:21:44.660] [ERROR] [TSED] - { inspect: [Function: inspect] }
```
